function(maru_unity_sources OUT_VAR)
    set(files ${ARGN})
    set(unity_file ${CMAKE_CURRENT_BINARY_DIR}/unity_build.c)
    file(WRITE ${unity_file} "/* Auto-generated unity build */\n")
    foreach(f IN LISTS files)
        file(APPEND ${unity_file} "#include \"${f}\"\n")
    endforeach()
    set(${OUT_VAR} ${unity_file} PARENT_SCOPE)
endfunction()